### ISSUE TITLE
PACS Query result buttons broken

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ui#938]
![image](https://github.com/FNNDSC/ChRIS_ui/assets/20404439/3217c12b-9635-4df5-877b-3da174012769)

After a PACS series is pulled, two buttons are presented on hover: "Created Feed" and "Preview"

https://github.com/FNNDSC/ChRIS_ui/blob/cbc71ea8bac1d26b22a810c1b8c0d095a0640767/src/pages/DataLibrary/components/PACSLookup/QueryResults.tsx#L463-L483

Both of these buttons are currently broken.

## Create Feed Button

Clicking on this button does nothing. In the console you get

```
Uncaught TypeError: createFeed is not a function
```

This has been broken since #628. The last working build is `ghcr.io/fnndsc/chris_ui:20220909.95-59fad388`

## Preview

![image](https://github.com/FNNDSC/ChRIS_ui/assets/20404439/c5fdd039-2f38-439e-a334-b2368e3f4656)

Does not show anything. I did not dig into this bug.
